services:
  frontend:
    image: stringlabtech/frontend:${VERSION}
    build:
      dockerfile: docker/dockerfiles/frontend.Dockerfile
      context: ..
  backend:
    image: stringlabtech/backend:${VERSION}
    build:
      dockerfile: docker/dockerfiles/backend.Dockerfile
      context: ..
  runner:
    image: unstract/runner:${VERSION}
    build:
      dockerfile: docker/dockerfiles/runner.Dockerfile
      context: ..
  platform-service:
    image: unstract/platform-service:${VERSION}
    build:
      dockerfile: docker/dockerfiles/platform.Dockerfile
      context: ..
  prompt-service:
    image: unstract/prompt-service:${VERSION}
    build:
      dockerfile: docker/dockerfiles/prompt.Dockerfile
      context: ..
  x2text-service:
    image: unstract/x2text-service:${VERSION}
    build:
      dockerfile: docker/dockerfiles/x2text.Dockerfile
      context: ..
